# ---------------------------------------------------------
# LAYER 1:BASE IMAGE micromamba
# ---------------------------------------------------------
FROM mambaorg/micromamba:latest

# -----------------------
# Build Arguments
# -----------------------
ARG IMAGE_NAME=open3d-pytorch-cuda
ARG IMAGE_REPO=geektechnophile
ARG IMAGE_VERSION=1.0

# -----------------------
# Prevent prompts during installs
# -----------------------
ENV DEBIAN_FRONTEND=noninteractive

# -----------------------
# Metadata
# -----------------------
LABEL maintainer="geektechnophile@gmail.com"
LABEL description="Docker image with Open3D & PyTorch(CUDA12.5) on micromamba as base image"
LABEL version="1.0"
LABEL gpu.required="true"
LABEL gpu.compute_capability="8.6"
LABEL gpu.memory="8GB"
# ---------------------------------------------------------
# LAYER 2: Create Python 3.11 environment
# ---------------------------------------------------------
RUN micromamba create -n open3d-pytorch-env python=3.11 -y \   && micromamba clean --all --yes

# -----------------------------
# LAYER 3: Install packages from open3d wheel
# -------------------------------
RUN micromamba run -n open3d-pytorch-env \
    pip install --no-cache \
        open3d==0.18.0 \
        && micromamba clean --all --yes

# -------------------------------
# Install packages from pytorch.org
# -------------------------------
# LAYER 4:
RUN micromamba run -n open3d-pytorch-env pip install --no-deps --no-cache \
    nvidia-cuda-nvrtc==13.0.48 --index-url https://download.pytorch.org/whl/cu130 && micromamba clean --all --yes
# LAYER 5:
RUN micromamba run -n open3d-pytorch-env pip install --no-deps --no-cache \
    nvidia-cuda-runtime==13.0.48 --index-url https://download.pytorch.org/whl/cu130 && micromamba clean --all --yes
# LAYER 6:
RUN micromamba run -n open3d-pytorch-env pip install --no-deps --no-cache \
    nvidia-cuda-cupti==13.0.48 --index-url https://download.pytorch.org/whl/cu130 && micromamba clean --all --yes
# LAYER 7:
RUN micromamba run -n open3d-pytorch-env pip install --no-deps --no-cache \
    nvidia-cudnn-cu13==9.13.0.50 --index-url https://download.pytorch.org/whl/cu130 && micromamba clean --all --yes
# LAYER 8:
RUN micromamba run -n open3d-pytorch-env pip install --no-deps --no-cache \
    nvidia-cublas==13.0.0.19 --index-url https://download.pytorch.org/whl/cu130 && micromamba clean --all --yes
# LAYER 9:
RUN micromamba run -n open3d-pytorch-env pip install --no-deps --no-cache \
    nvidia-cufft==12.0.0.15 --index-url https://download.pytorch.org/whl/cu130 && micromamba clean --all --yes
# LAYER 10:
RUN micromamba run -n open3d-pytorch-env pip install --no-deps --no-cache \
    nvidia-curand==10.4.0.35 --index-url https://download.pytorch.org/whl/cu130 && micromamba clean --all --yes
# LAYER 11:
RUN micromamba run -n open3d-pytorch-env pip install --no-deps --no-cache \
    nvidia-cusolver==12.0.3.29 --index-url https://download.pytorch.org/whl/cu130 && micromamba clean --all --yes
# LAYER 12:
RUN micromamba run -n open3d-pytorch-env pip install --no-deps --no-cache \
    nvidia-cusparse==12.6.2.49 --index-url https://download.pytorch.org/whl/cu130 && micromamba clean --all --yes
# LAYER 13:
RUN micromamba run -n open3d-pytorch-env pip install --no-deps --no-cache \
    nvidia-cusparselt-cu13==0.8.0 --index-url https://download.pytorch.org/whl/cu130 && micromamba clean --all --yes
# LAYER 14:
RUN micromamba run -n open3d-pytorch-env pip install --no-deps --no-cache \
    nvidia-nccl-cu13==2.27.7 --index-url https://download.pytorch.org/whl/cu130 && micromamba clean --all --yes
# LAYER 15:
RUN micromamba run -n open3d-pytorch-env pip install --no-deps --no-cache \
    nvidia-nvshmem-cu13==3.3.24 --index-url https://download.pytorch.org/whl/cu130 && micromamba clean --all --yes
# LAYER 16:
RUN micromamba run -n open3d-pytorch-env pip install --no-deps --no-cache \
    nvidia-nvtx==13.0.39 --index-url https://download.pytorch.org/whl/cu130 && micromamba clean --all --yes
# LAYER 17:
RUN micromamba run -n open3d-pytorch-env pip install --no-deps --no-cache \
    nvidia-nvjitlink==13.0.39 --index-url https://download.pytorch.org/whl/cu130 && micromamba clean --all --yes
# LAYER 18:
RUN micromamba run -n open3d-pytorch-env pip install --no-deps --no-cache \
    nvidia-cufile==1.15.0.42 --index-url https://download.pytorch.org/whl/cu130 && micromamba clean --all --yes
# LAYER 19:  
RUN micromamba run -n open3d-pytorch-env pip install --no-deps --no-cache \
    torch==2.9.0+cu130 --index-url https://download.pytorch.org/whl/cu130 && micromamba clean --all --yes
# LAYER 20: 
RUN micromamba run -n open3d-pytorch-env pip install --no-deps --no-cache \
    triton==3.5.0 --index-url https://download.pytorch.org/whl/cu130 && micromamba clean --all --yes
# LAYER 21: 
RUN micromamba run -n open3d-pytorch-env pip install --no-deps --no-cache \
    triton==3.5.0 --index-url https://download.pytorch.org/whl/cu130 && micromamba clean --all --yes

# ------------------------------------------
# install jupyter lab
# ------------------------------------------
RUN micromamba run -n open3d-pytorch-env \
    pip install --no-cache \
    notebook jupyterlab \
    && micromamba clean --all --yes

# ------------------------------------------
# Switch to root to install system libraries
# ------------------------------------------
USER root

# -----------------------
# LAYER 22: BASE IMAGE DEPENDENCES
# -----------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 libgl1 && \
    rm -rf /var/lib/apt/lists/*

# -----------------------
# Set working directory
# -----------------------
WORKDIR /workspace

# Switch back to default shell for following commands
SHELL ["bash", "-c"]


